NoneType Error Handling on sync_products
Handling error where, actual_qty or reserved_qty are None
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'